### PR TITLE
Allow php 8.3

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by Ocramius** [comment]
Ha, chicken-egg scenario.

Perhaps we can remove `ocramius/package-versions` and rely on the `composer-runtime-api` instead? I don't even remember where it is used :D

**Comment by fezfez** [comment]
@Ocramius done, and i've moved the deps in require-dev

**Comment by Ocramius** [comment]
Seems like sources still use the other package? 🤔

**Comment by fezfez** [comment]
> Seems like sources still use the other package? 🤔

my bad it was in bin/ folder

**Comment by fezfez** [comment]
ping !

**Review by Ocramius — APPROVED** [review]
Thanks @fezfez!

**Pull request merged**
