### PR TITLE
Update infection/infection to 0.26.1 version

### PR DESCRIPTION
**Pull request by devanych**
See: https://github.com/yiisoft/strings/pull/77, https://github.com/infection/infection/issues/1643 and https://github.com/infection/infection/pull/1644

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
`composer.lock` also needs updating

**Comment by devanych** [comment]
> `composer.lock` also needs updating

Done.

**Comment by devanych** [comment]
`github-actions` has already updated the version https://github.com/Roave/infection-static-analysis-plugin/commit/d75c3bdf5d593343e9aed532eef61de0ef840951. Need tag `1.15.0` :)

**Comment by Ocramius** [comment]
Was merged in #297, sorry :|

Closing as `duplicate` here.

**Pull request closed without merging**
